TodoAppIdentityMvc/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TodoAppIdentityMvc.Core.Interfaces;
using TodoAppIdentityMvc.Models.Entities;
using TodoAppIdentityMvc.Utiles;
using static System.Reflection.Metadata.BlobBuilder;

namespace TodoAppIdentityMvc.Controllers
{
    public class HomeController : Controller
    {
        private readonly ITodoService _todoService;

        public HomeController(ITodoService todoService)
        {
            _todoService = todoService;
        }

        public async Task<IActionResult> Index(string filterString)
        {
            var todos = await _todoService.GetUserTodoAsync(User);
            switch (filterString)
            {
                case StaticeFilterStrings.TODAY:
                    /* This approach will work only if todos has already been loaded into memory (e.g., if it's a List<T>).
                     * If it's a database query, DateTime.Date is not translatable to SQL, so you'll need to use a range comparison instead. */
                    todos = todos.Where(t => t.CreatedAt.Date == DateTime.Now.Date).ToList();
                    break;
                case StaticeFilterStrings.COMPLETED:
                    todos = todos.Where(t => t.IsCompleted == true).ToList();
                    break;
                case StaticePriorities.HIGH:
                    todos = todos.Where(t => t.Priority == StaticePriorities.HIGH).ToList();
                    break;
                case StaticePriorities.MEDIUM:
                    todos = todos.Where(t => t.Priority == StaticePriorities.MEDIUM).ToList();
                    break;
                case StaticePriorities.LOW:
                    todos = todos.Where(t => t.Priority == StaticePriorities.LOW).ToList();
                    break;
                default:
                    break;
            }
            return View(todos);
        }

        public IActionResult Privacy()
        {
            return View();
        }

    }
}

TodoAppIdentityMvc/Controllers/TodoController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using TodoAppIdentityMvc.Core.Interfaces;
using TodoAppIdentityMvc.Models.Dtos;
using TodoAppIdentityMvc.Utiles;

namespace TodoAppIdentityMvc.Controllers
{
    public class TodoController : Controller
    {
        private readonly ITodoService _todoService;

        public TodoController(ITodoService todoService)
        {
            _todoService = todoService;
        }

        public IActionResult Create()
        {
            return PartialView("Create");
        }

        [HttpPost]
        public async Task<IActionResult> Create(TodoDto todoDto)
        {
            if (!ModelState.IsValid)
            {
                return View(todoDto);
            }
            var response = await _todoService.CreateTodoAsync(User, todoDto);
            if (response.IsSuccess)
            {
                TempData[StaticAlertMessage.SUCCESS] = response.Message;
                return RedirectToAction("Index", "Home");
            }
            TempData[StaticAlertMessage.ERROR] = response.Error;
            return View(response);
        }

        public async Task<IActionResult> Edit(string id)
        {
            var response = await _todoService.GetTodoByIdAsync(id);
            if (response.IsSuccess)
            {
                return PartialView("Edit", response.Data);
            }
            TempData[StaticAlertMessage.ERROR] = response.ErrorMessage;
            return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        public async Task<IActionResult> Edit(string id, BaseTodoDto editTodoDto)
        {
            if (!ModelState.IsValid)
            {
                return View(editTodoDto);
            }
            var response = await _todoService.EditTodoAsync(id, editTodoDto);
            if (response.IsSuccess)
            {
                TempData[StaticAlertMessage.SUCCESS] = response.Message;
                return RedirectToAction("Index", "Home");
            }

            TempData[StaticAlertMessage.ERROR] = response.Error;
            return View(editTodoDto);
        }

        public async Task<IActionResult> Delete(string id)
        {
            var response = await _todoService.GetTodoByIdAsync(id);
            if (response.IsSuccess)
            {
                return View(response.Data);
            }
            TempData[StaticAlertMessage.ERROR] = response.ErrorMessage;
            return RedirectToAction("Index", "Home");
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteTodo(string id)
        {
            var response = await _todoService.DeleteTodoAsync(id);
            if(response.IsSuccess)
            {
                TempData[StaticAlertMessage.SUCCESS] = response.Message;
                return RedirectToAction("Index", "Home");
            }

            TempData[StaticAlertMessage.ERROR] = response.Error;
            return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        public async Task<IActionResult> Complete(string id)
        {
            var response = await _todoService.CompleteTodoAsync(id);
            if (response.IsSuccess)
            {
                return RedirectToAction("Index", "Home");
            }

            TempData[StaticAlertMessage.ERROR] = response.Error;
            return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        public async Task<IActionResult> AddToArchvie(string id)
        {
            var response = await _todoService.AddToArchiveAsync(id, User);
            if (response.IsSuccess)
            {
                TempData[StaticAlertMessage.SUCCESS] = response.Message;
                return RedirectToAction("Index", "Home");
            }

            TempData[StaticAlertMessage.ERROR] = response.Error;
            return RedirectToAction("Index", "Home");
        }

        [Authorize]
        public async Task<IActionResult> Archive()
        {
            var todos = await _todoService.GetUserArchivedTodoAsync(User);
            return View(todos);
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Search(string searchString)
        {
            var todos = await _todoService.SerachTodoAsync(searchString, User);
            return View(todos);
        }

    }
}

TodoAppIdentityMvc/Views/Home/Index.cshtml
@model List<Todo>

@{
    ViewData["Title"] = "Home Page";
}

<partial name="_ShowMessage"></partial>

@if (!User.Identity.IsAuthenticated)
{
    <div class="home-screen">
        <h1 class="home__title">orgnize your tasks effortlessly</h1>
        <p class="home__descrpition">
            Lorem ipsum dolor sit amet consectetur adipisicing elit. At vero
            delectus reiciendis libero mollitia porro omnis, error neque aut possimus nostrum nobis id nemo
            fuga enim, minima odio assumenda temporibus!
        </p>
        <a asp-controller="Account" asp-action="Login" class="home__link">get started</a>
    </div>
}
else
{
    if (!Model.Any())
    {
        <p class="no-result">No todo make one!</p>
    }
    else
    {
        <div class="main-content-wrapper">
            @foreach (var todo in Model)
            {
                <div class="item-card">
                    <div class="flex items-center gap-05 m-b-1 justify-end">
                        <button onclick="OpenEditModal('@todo.Id')" class="item-card__action-link">
                            <div class="action-icon action-icon--edit">
                                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
                                     stroke-width="1.5" stroke="currentColor" class="size-6">
                                    <path stroke-linecap="round" stroke-linejoin="round"
                                          d="m16.862 4.487 1.687-1.688a1.875 1.875 0 1 1 2.652 2.652L10.582 16.07a4.5 4.5 0 0 1-1.897 1.13L6 18l.8-2.685a4.5 4.5 0 0 1 1.13-1.897l8.932-8.931Zm0 0L19.5 7.125M18 14v4.75A2.25 2.25 0 0 1 15.75 21H5.25A2.25 2.25 0 0 1 3 18.75V8.25A2.25 2.25 0 0 1 5.25 6H10" />
                                </svg>
                            </div>
                        </button>
                        <a asp-controller="Todo" asp-action="Delete" asp-route-id="@todo.Id" class="item-card__action-link">
                            <div class="action-icon action-icon--delete">
                                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
                                     stroke-width="2" stroke="currentColor" class="size-6">
                                    <path stroke-linecap="round" stroke-linejoin="round"
                                          d="m14.74 9-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 0 1-2.244 2.077H8.084a2.25 2.25 0 0 1-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 0 0-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 0 1 3.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 0 0-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 0 0-7.5 0" />
                                </svg>
                            </div>
                        </a>
                    </div>
                    <!-- remove completed class -->
                    <h2 class="item__title @(todo.IsCompleted ? "item__title--completed" : "")">@todo.Title</h2>
                    <div class="item-card__info-wrapper">
                        <p class="item__date">@(todo.CreatedAt.ToShortDateString().Replace("/", "-"))</p>
                        <p class="item__priority @(todo.Priority == StaticePriorities.HIGH ? "item__priority--high" : todo.Priority == StaticePriorities.MEDIUM ? "item__priority--medium" : "item__priority--low")">@todo.Priority</p>
                    </div>
                    <div class="item-card__form-wrapper">
                        @if (todo.InArchive)
                        {
                            <!-- Remove the display-none class -->
                            <div>
                                <p class="item__add-to-archive--para">added to archive</p>
                            </div>
                        }
                        else
                        {
                            <form asp-controller="Todo" asp-action="AddToArchvie" asp-route-id="@todo.Id" method="post">
                                <button type="submit" class="item__add-to-archive">add to archive</button>
                            </form>
                        }
                        <form asp-controller="Todo" asp-action="Complete" asp-route-id="@todo.Id" class="item__form-completed" method="post">
                            <input asp-for="@todo.IsCompleted" class="item__complete-input" type="checkbox" id="@todo.Id">
                            <label for="@todo.Id">completed?</label>
                        </form>
                    </div>
                </div>
            }
        </div>

    }
}


@section Scripts {
    <script>
       const inputes =  document.querySelectorAll('.item__complete-input');
       const forms = document.querySelectorAll('.item__form-completed');
       inputes.forEach(input => {
            input.addEventListener("change", (e) => {
                 e.target.closest('form').submit()
            })
       })
    </script>
}